### ISSUE TITLE
Docs for -x are wrong

### ISSUE THREAD

**Issue by seanmcl** [pgr0ss/bazel-deps#11]
Looks like it means "exclude" now rather than "transitive"

**Comment by pgr0ss** [comment]
Can you clarify where you see the incorrect docs?

**Comment by seanmcl** [comment]
```
$ java -jar target/bazel-deps-2.0-SNAPSHOT.jar
Usage: java -jar bazel-deps-1.0-SNAPSHOT [VAL ...] [-x VAL]
 VAL    : <artifact id>
 -x VAL : Exclude a libraries dependencies
```

But the docs say it's for including transitive dependencies.

**Comment by seanmcl** [comment]
Oops, I misread.  Sorry.  You say "exclude a library's deps".

**Comment by pgr0ss** [comment]
No worries. I thought I was missing something.
