### ISSUE TITLE
How is this different from Bazel's generate_workspace?

### ISSUE THREAD

**Issue by ittaiz** [pgr0ss/bazel-deps#8]
Hi,
Stumbled across this repo and it looks interesting, thanks!
How is this different from Bazel's [generate_workspace](http://www.bazel.io/docs/external.html#transitive-dependencies)?

**Comment by pgr0ss** [comment]
At this point, you should probably just use bazel's `generate_workspace`. When I made this project, bazel's script was much more primitive.

**Comment by ittaiz** [comment]
Fair enough, thanks for the answer!
